### PR TITLE
New features

### PR DESCRIPTION
**Pull request by XaviTechEc**
Look at this new features.

### CODE REVIEW

**Comment by XavierGM23** [comment]
Why yarn if you are using npm ?

**Review by XavierGM23 — CHANGES_REQUESTED** [review]
Please get rid of this changes. @XaviTechEc

**Comment by XaviTechEc** [comment]
@XavierGM23 Changes already done 👍🏼

**Comment by XavierGM23** [comment]
LGTM!

**Review by XavierGM23 — APPROVED** [review]
LGTM!

**Pull request merged**
